name: Get Latest Tag from Manual Approval Issue
author: toppulous
branding:
  color: purple
  icon: message-square
description: Retrives tag information from comments in given issue number
inputs:
  issue-number:
    descirption: number of issue to get latest tag from (generally, a manual approval issue that was just closed)
    required: true
  keyword:
    description: keyword used in update-manual-approval-issue
    required: false
    default: GITHUB_ACTIONS
  github-token:
    description: token used to create authenticated client
    required: false
    default: ${{ github.token }}
outputs:
  tag:
    description: the latest tag on the approved issue
runs:
  using: node12
  main: index.js
